#!/bin/bash

cpunum=`cat /proc/cpuinfo | grep name | wc -l`
if [ $cpunum -gt 1 ]
then
		echo "Litmus should run on smp"
		exit 0
else
		echo "RISC-V Litmus Test"
fi

if [ -f "/usr/bin/litmus/run.exe" ]; then
	echo " run litmus test with mixed param"
	
else
	echo "litmus doesn't exist!!!"
fi